// <auto-generated />
using System;
using EnergiasRenovables.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergiasRenovables.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.Biomasa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ContenidoEnergetico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoConversion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Biomasa");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaEolica", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AlturaTurbinas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiametroTurbina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroTurbinas")
                        .HasColumnType("int");

                    b.Property<decimal>("VelocidadViento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EnergiaEolicas");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaGeotermica", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Caudal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroPozos")
                        .HasColumnType("int");

                    b.Property<decimal>("TemperaturaFluidos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EnergiaGeotermicas");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaHidroelectrica", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Caudal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroTurbinas")
                        .HasColumnType("int");

                    b.Property<decimal>("Salto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EnergiaHidroelectricas");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaRenovable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEnergiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoEnergiaId");

                    b.ToTable("EnergiasRenovables");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaSolar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AnguloInclinacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AreaPaneles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EficienciaPaneles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RadiacionSolar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EnergiaSolars");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.Pais", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("EnergiaRequerida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NivelCovertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaProduccionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Poblacion")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.PlantaProduccion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("CapacidadInstalada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Eficiencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantaProduccions");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.TipoEnergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEnergias");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.Biomasa", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.EnergiaRenovable", "EnergiaRenovable")
                        .WithOne("Biomasa")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.Biomasa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergiaRenovable");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaEolica", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.EnergiaRenovable", "EnergiaRenovable")
                        .WithOne("EnergiaEolica")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.EnergiaEolica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergiaRenovable");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaGeotermica", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.EnergiaRenovable", "EnergiaRenovable")
                        .WithOne("EnergiaGeotermica")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.EnergiaGeotermica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergiaRenovable");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaHidroelectrica", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.EnergiaRenovable", "EnergiaRenovable")
                        .WithOne("EnergiaHidroelectrica")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.EnergiaHidroelectrica", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergiaRenovable");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaRenovable", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.PlantaProduccion", "PlantaProduccion")
                        .WithOne("EnergiaRenovable")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.EnergiaRenovable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergiasRenovables.Model.Entities.TipoEnergia", "TipoEnergia")
                        .WithMany("EnergiasRenovables")
                        .HasForeignKey("TipoEnergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantaProduccion");

                    b.Navigation("TipoEnergia");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaSolar", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.EnergiaRenovable", "EnergiaRenovable")
                        .WithOne("EnergiaSolar")
                        .HasForeignKey("EnergiasRenovables.Model.Entities.EnergiaSolar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergiaRenovable");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.PlantaProduccion", b =>
                {
                    b.HasOne("EnergiasRenovables.Model.Entities.Pais", "Pais")
                        .WithMany("PlantaProduccion")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.EnergiaRenovable", b =>
                {
                    b.Navigation("Biomasa")
                        .IsRequired();

                    b.Navigation("EnergiaEolica")
                        .IsRequired();

                    b.Navigation("EnergiaGeotermica")
                        .IsRequired();

                    b.Navigation("EnergiaHidroelectrica")
                        .IsRequired();

                    b.Navigation("EnergiaSolar")
                        .IsRequired();
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.Pais", b =>
                {
                    b.Navigation("PlantaProduccion");
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.PlantaProduccion", b =>
                {
                    b.Navigation("EnergiaRenovable")
                        .IsRequired();
                });

            modelBuilder.Entity("EnergiasRenovables.Model.Entities.TipoEnergia", b =>
                {
                    b.Navigation("EnergiasRenovables");
                });
#pragma warning restore 612, 618
        }
    }
}
